
export const DefaultImagePreviewOptions = {
    autoGenerate: true,
    generateFileInfo: true,
    attributeName: "src",
    tagName: "img",
    tagId: "",
    tagClass: "blazor-form-manager-image-preview",
    autoGeneratedClass: "form-manager-auto-generated",
    wrapperSelector: ".image-wrapper",
    width: 150,
    height: 0,
    preserveAspectRatio: true,
    noResize: false,
};

export const SIZE_KB = 1024;
export const SIZE_MB = SIZE_KB * SIZE_KB;
export const SIZE_GB = SIZE_KB * SIZE_MB;
export const SIZE_TB = SIZE_KB * SIZE_GB;
export const PRIMITIVES = ["string", "number", "bigint", "boolean"];

export const AssemblyName = 'BlazorFormManager';
export const Forms: IDictionary<FormManagerOptions> = {};
export const DragDropStorage: IDictionary<DragDropOptions> = {};
